### ISSUE TITLE
Does not seem to follow directional settings

### ISSUE THREAD

**Issue by GamerRaven81** [Jods-GH/AutoDoors#1]
### Description

When the doors open, they dont seem to follow the directional setting (Always In/Always Out) settings.

### Ark Game Version

26.2

### Which version are you playing?

Server user (Default)

### mod Version

1

### Tested with only the Mod loaded

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Use the door

**Comment by Jodsderechte** [comment]
this was fixed  in v8
