### ISSUE TITLE
Stone tier dino gate missing options

### ISSUE THREAD

**Issue by AnsgarTOdinson** [Jods-GH/AutoDoors#10]
### Description

The stone tier dino gate doesnt have the option to change behavior of the gate.  Cannot, for instance, choose auto close only. 

### Ark Game Version

33.15(CL476710)

### Which version are you playing?

Server owner (the server specific version)

### mod Version

21

### Tested with only the Mod loaded

- [X] Yes
- [ ] No

### Reproduction Steps

Build a stone tier dino gate auto door.

**Comment by Jodsderechte** [comment]
this is already fixed and just waiting for curseforge to publish the release (prob gonna take till after the holidays)
