### ISSUE TITLE
Autodoors on behemoth gates causes server crashes.

### ISSUE THREAD

**Issue by brothasx** [Jods-GH/AutoDoors#12]
### Description

Autodoors on behemoth gates are the cause of server crashes.
When a person try to open a behemoth autodoor gate, the server crashes.

Cant give more info about it, just that i came to the conclusion that everytime the server crashes it is because a person opened / closed a behemoth gate with autodoor installed. 

There are multiple server owners having issues with these crashes. 

Hope you can find a fix / reproduce the issue. 

 

### Ark Game Version

33.63

### Which version are you playing?

Server owner (the server specific version)

### mod Version

latest

### Tested with only the Mod loaded

- [ ] Yes
- [X] No

### log

ÿþFatal error!

Unhandled Exception: EXCEPTION_STACK_OVERFLOW

CL: 478694
0x00007ff76ce7be4b ArkAscendedServer.exe!HashLowerCase() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\Core\Private\UObject\UnrealNames.cpp:883]
0x00007ff76ce6daba ArkAscendedServer.exe!FNamePool::Store() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\Core\Private\UObject\UnrealNames.cpp:1705]
0x00007ff76ee00adb ArkAscendedServer.exe!UKismetSystemLibrary::K2_ClearTimer() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\Engine\Private\KismetSystemLibrary.cpp:658]
0x00007ff76edf094c ArkAscendedServer.exe!UKismetSystemLibrary::execK2_ClearTimer() [E:\dave_WC-PURPLERAIN_NVidia\Projects\ShooterGame\Intermediate\Build\Win64\ShooterGameServer\Inc\Engine\UHT\KismetSystemLibrary.gen.cpp:2444]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedServer.exe!UObject::execLocalVirtualFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3205]
0x00007ff76d0427e8 ArkAscendedServer.exe!ProcessLocalScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1203]
0x00007ff76d04ccd6 ArkAscendedServer.exe!ProcessScriptFunction() [E:\dave_WC-PURPLERAIN_NVidia\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1033]
0x00007ff76d04777c ArkAscendedSLast Replicated Actor SingletonDinoDepot_C_2147139511
Last Remote Function PlayHitEffectPoint

### Reproduction Steps

Hard to replicate,

We just know it has to do with the Behemoth gates,

Multiple server owners are having this issue.

**Comment by Jodsderechte** [comment]
Is it any specific behemoth gate or in general? Also are you using the qol÷ mod with the resource transfer gun? Someone mentioned they were able to crash the server reliably with that gun. However I've been using behemoth gates on my server since release and have not had issues. Can you give me your full modlist and tell me if you are using any plug-ins?

**Comment by brothasx** [comment]
I am using Lethal decay and itemsplus. 

We do use the Qol + mod as well.

So far when i asked the players what they were doing right before the crash, the person was opening a STONE behemoth gate. 

A other server owner just informed me, he had his server crash twice by riding a Burning Equus and going through a auto stone behemoth gate. 

i will list here the mod list of another server owner with the same issues ( since he has less mods and might narrow it down) 


Auto Doors
Automated Ark
Awesome Spyglass!
Crafting Skill Potion
Der Dino Finder
Dino Depot
Items Plus Ascended
Inventory Backup Saver
Lily's Tweaker
MX-E Ark Shop UI
QoL+
Shiny! Dinos Ascended
Solo Farm Mod
Sqaw's Flyers

**Comment by brothasx** [comment]
So far we have been using the transfergun for months now, but never had any crash because of that. 
These crashes started happening about a week ago.

**Comment by Jodsderechte** [comment]
Is the other server owner also using plug-ins?

**Comment by brothasx** [comment]
Yes he does, he is using.. ( asking for it) 
![image](https://github.com/Jods-GH/AutoDoors/assets/49365370/21a7a054-2e1b-42e6-bf7c-82e73532cf2d)

**Comment by Jodsderechte** [comment]
I did some investigation and couldn't figure out why this is happening. I pushed more agressive bug prevention but not much more i can do If you can narrow this issue down to a more specific problem i can try to fix it otherwise It's prob some interaction with some plugin or mod or the plugin api itself
