### ISSUE TITLE
Unable to place autodoor

### ISSUE THREAD

**Issue by Adaptabull** [Jods-GH/AutoDoors#15]
### Description

Im on PC, while holding/pressing the "R" Key does not open up a menu while I am placing a door. Attempting to use Stone Gateway Door.

### Ark Game Version

48.12 (CL 564295)

### Which version are you playing?

Singleplayer

### mod Version

36

### Tested with only the Mod loaded

- [X] Yes
- [ ] No

### Reproduction Steps

Using the steps provided in the mod info, I was unable to produce an AutoDoor

**Comment by Jodsderechte** [comment]
Tested as of 1 min ago this still works. Tested on both dedicated server and Singleplayer. Make sure to have the mod enabled and reinstall it if it doesn't work

**Comment by Adaptabull** [comment]
Oof, It wasn't enabled. Sorry, new ark player here. It's working, thank you! Awesome mod btw, probably the only one I'm going to be using.
