### ISSUE TITLE
Cellar Support

### ISSUE THREAD

**Issue by Excelsies** [Jods-GH/AutoDoors#2]
### Is your feature request related to a problem? Please describe.

I have a few bases that have a ceiling above where I store my dinos to prevent wild dinos/players from easily accessing my base from above. I use a behemoth cellar door for easy access for my flying tames. Unfortunately, this mod isn't working with the cellar doors.

### Describe the solution you'd like

It'd be fantastic if this would work for cellar doors so I don't have to open it before grabbing the tame and closing it behind the tame.

**Comment by runamonk** [comment]
This is a good one.

**Comment by Jodsderechte** [comment]
I tried finding the cellar doors before but the names seems to be different. If anyone cna point me towards or I can find their names I'd love to add them

**Comment by Jodsderechte** [comment]
This should be implemented now if you find any issues let me know
