### ISSUE TITLE
Add door close delay or take dinosaurs into account when closing

### ISSUE THREAD

**Issue by runamonk** [Jods-GH/AutoDoors#3]
### Is your feature request related to a problem? Please describe.

Right now when you approach the door it opens as it should however once your character is through the door starts to close, the issue is when riding larger dinos it closes on the doors. 

### Describe the solution you'd like

So really adding a door close delay option would help. This would be really helpful when creating taming traps.

**Comment by Jodsderechte** [comment]
@NeoTiger  closing triggers as soon as the player has left the vicinity that would open the door. Atleast thats how it is supposed to work and does so in testing. If it doesn't, that would be a bug. And it would be best if you made a ticket for it (preferably with a video)

**Comment by runamonk** [comment]
All you need to do is two things:

1. Try and tow a tame through the gate, super annoying.
2. Ride a large tame through the door. Again super annoying to do.

**Comment by Jodsderechte** [comment]
Already working on having the settings. In the latest release only wooden doors have setting and it's only changing between full automatic/manual/auto close only doors. Delay is in the works but prob next Weekend at the earliest.

**Comment by runamonk** [comment]
That sounds perfect.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jodsderechte** [comment]
Delay seems to be a much larger project that would best be paused until a bit later when wildcard released a new system for their structures. However i might have some different solution ideas. What is general the usecase for an auto close delay? Is it just having dino on follow get through the door?

**Comment by JHiebert92** [comment]
Dinos on follow, and also large mounted dinosaurs that aren't entirely through the gate by the time they start closing on you. If a delay isn't possible, perhaps having the doors react to mounted/following tames would work.

**Comment by Jodsderechte** [comment]
That was my initial idea yes. Although mounted tames should work properly now. I'll also look into following tames

**Comment by Jodsderechte** [comment]
this should be  working now in newest version
