### ISSUE TITLE
Xbox support

### ISSUE THREAD

**Issue by madlax72** [Jods-GH/AutoDoors#7]
### Is your feature request related to a problem? Please describe.

It would be awesome if you could get this to work for Xbox. I'm running a private server and just joined a character I created on Xbox. The doors are all invisible at my base, but still provide a barrier. 

### Describe the solution you'd like

Make it work on Xbox and hopefully PS5 when ASA releases

Thank you!

**Comment by Jodsderechte** [comment]
this was added with last release
