### ISSUE TITLE
New door features.

### ISSUE THREAD

**Issue by Rashaka11** [Jods-GH/AutoDoors#8]
### Is your feature request related to a problem? Please describe.

Doors frequently close on your dinos with dealing with larger than person sized doors.

### Describe the solution you'd like

Add options for auto open or auto close only.

Reduce the range at which you trigger the behemoth doors to open and add an optional delay for how long all dino doors should stay open after being triggered.

**Comment by ELSalvadore** [comment]
That would be great if this function existed and you could change the door later:
Add options for auto open or auto close only.
