### ISSUE TITLE
Cant Place Autodoors

### ISSUE THREAD

**Issue by ReapersWrath** [Jods-GH/AutoDoors#9]
### Description

Im unable to place any autodoors starting today 

### Ark Game Version

32.24

### Which version are you playing?

Server owner (the server specific version)

### mod Version

1

### Tested with only the Mod loaded

- [ ] Yes
- [ ] No

### Reproduction Steps

place an autodoor

**Comment by Jodsderechte** [comment]
You completly ignored the error form. Not enough details. And i tested it on my server works without any issues
